Parameters:
  databasepassword:
    Description: Database password 
    Type: String
    Default: Password1234
  pinpointprojectid:
    Description: Pinpoint project id 
    Type: String
  smsflag:
    Description: Send SMS flag 
    Type: String
    Default: true
  datasourceurl:
    Description: RDS Database Endpoint 
    Type: String
  domainname:
    Description: Domain name 
    Type: String
    Default: http://url.mayurbhagia.online/
  countrycode:
    Description: Country Code for SMS
    Type: String
    Default: +91   
  pinpointsenderid:
    Description: Pinpoint SMS Sender Id
    Type: String
    Default: ""
  pinpointregisteredkeyword:
    Description: Pinpoint SMS Keyword
    Type: String
    Default: ""
  pinpointentityId:
    Description: Pinpoint Principal Entity Id
    Type: String
    Default: ""  
  pinpointtemplateId:
    Description: Pinpoint Template Id
    Type: String
    Default: ""             
  urlretention:
    Description: Pinpoint URL Retention in Days
    Type: String
    Default: 30    
Resources:

  URLShortenerSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "/urlshortner/sm/URLShortenerApplication"    
      Description: This is urlshortener secrets manager
      SecretString: !Join
        - ""
        - - "{\"spring.datasource.username\": \"master\",\"spring.datasource.password\":\""
          - !Ref databasepassword
          - "\""
          - ",\"urlshort.smsflag\":\""
          - !Ref smsflag
          - "\""
          - ",\"urlshort.pinpointappid\":\""    
          - !Ref pinpointprojectid
          - "\""
          - ",\"spring.datasource.url\":\"jdbc:mysql://"
          - !Ref datasourceurl
          - ":3306/urlshortener?allowPublicKeyRetrieval=true&useSSL=FALSE\""
          - ",\"urlshort.domainname\":\""
          - !Ref domainname
          - "\""          
          - ",\"urlshort.countrycode\":\""
          - !Ref countrycode 
          - "\""          
          - ",\"urlshort.pinpointsenderid\":\""
          - !Ref pinpointsenderid
          - "\""          
          - ",\"urlshort.pinpointregisteredkeyword\":\""
          - !Ref pinpointregisteredkeyword
          - "\""
          - ",\"urlshort.pinpointentityId\":\""
          - !Ref pinpointentityId
          - "\""  
          - ",\"urlshort.pinpointtemplateId\":\""
          - !Ref pinpointtemplateId
          - "\""           
          - ",\"urlshort.urlretention\":\""
          - !Ref urlretention
          - "\""          
          - "}"
